server:
  port: 8080

spring:
  profiles:
    active: "local"
  application:
    name: mercantil-operations
  r2dbc:
    url: r2dbc:sqlserver://localhost:1433;databaseName=your_database
    username: your_username
    password: your_password

  #  data:
  #    mongodb:
  #      uri: mongodb://localhost:27017/your_database
  cloud:
    azure:
      keyvault:
        enabled: true
        uri: https://your-keyvault-name.vault.azure.net/

azure:
  secrets:
    secret-name: your_secret_name
  appinsight:
    instrumentationkey: your_instrumentation_key
  service-bus:
    topic-name: your_topic_name
    connection-string: your_service_bus_connection_string
  keyvault:
    properties:
      uri: https://your-keyvault-name.vault.azure.net/
      client-id: your-client-id
      client-secret: your-client-secret
      tenant-id: your-tenant-id

logging:
  level:
    root: info
    com.mercantil: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    mongodb:
      enabled: true
    r2dbc:
      enabled: true

adapter:
  restconsumer:
    anyrestconsume:
      baseurl: "localhost:8081" #Must be the path to consume
      somepath: "localhost:8081" #Must be the path to consume
mongodb:
  uri: "mongodb://localhost:27017/"
  database: "loansDB"

